# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TeensyTriggerSoftwareUI_v_a6_2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 281)
        font = QtGui.QFont()
        font.setPointSize(14)
        Form.setFont(font)
        Form.setMouseTracking(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.inputDisablePushButton = QtWidgets.QPushButton(self.groupBox_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.inputDisablePushButton.setPalette(palette)
        self.inputDisablePushButton.setAutoFillBackground(False)
        self.inputDisablePushButton.setCheckable(True)
        self.inputDisablePushButton.setDefault(False)
        self.inputDisablePushButton.setFlat(False)
        self.inputDisablePushButton.setObjectName("inputDisablePushButton")
        self.verticalLayout_9.addWidget(self.inputDisablePushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.SetGainlabel_2 = QtWidgets.QLabel(self.groupBox_4)
        self.SetGainlabel_2.setAutoFillBackground(False)
        self.SetGainlabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SetGainlabel_2.setObjectName("SetGainlabel_2")
        self.horizontalLayout_8.addWidget(self.SetGainlabel_2)
        self.Gaindropdown = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gaindropdown.sizePolicy().hasHeightForWidth())
        self.Gaindropdown.setSizePolicy(sizePolicy)
        self.Gaindropdown.setAcceptDrops(True)
        self.Gaindropdown.setAccessibleName("")
        self.Gaindropdown.setObjectName("Gaindropdown")
        self.Gaindropdown.addItem("")
        self.Gaindropdown.addItem("")
        self.Gaindropdown.addItem("")
        self.Gaindropdown.addItem("")
        self.horizontalLayout_8.addWidget(self.Gaindropdown)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.thresholdLevelVerticalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.thresholdLevelVerticalSlider.setMaximum(5000)
        self.thresholdLevelVerticalSlider.setSingleStep(10)
        self.thresholdLevelVerticalSlider.setSliderPosition(0)
        self.thresholdLevelVerticalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thresholdLevelVerticalSlider.setObjectName("thresholdLevelVerticalSlider")
        self.verticalLayout_7.addWidget(self.thresholdLevelVerticalSlider)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.thresholdLevelDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdLevelDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.thresholdLevelDoubleSpinBox.setSizePolicy(sizePolicy)
        self.thresholdLevelDoubleSpinBox.setKeyboardTracking(True)
        self.thresholdLevelDoubleSpinBox.setDecimals(3)
        self.thresholdLevelDoubleSpinBox.setMaximum(5.0)
        self.thresholdLevelDoubleSpinBox.setSingleStep(0.01)
        self.thresholdLevelDoubleSpinBox.setObjectName("thresholdLevelDoubleSpinBox")
        self.horizontalLayout_7.addWidget(self.thresholdLevelDoubleSpinBox)
        self.readLevelPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.readLevelPushButton.setObjectName("readLevelPushButton")
        self.horizontalLayout_7.addWidget(self.readLevelPushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.optimisePushButton = QtWidgets.QPushButton(self.groupBox)
        self.optimisePushButton.setObjectName("optimisePushButton")
        self.verticalLayout_4.addWidget(self.optimisePushButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.minFreqSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.minFreqSpinBox.setMaximum(1000000)
        self.minFreqSpinBox.setProperty("value", 1)
        self.minFreqSpinBox.setObjectName("minFreqSpinBox")
        self.horizontalLayout_2.addWidget(self.minFreqSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.FreqPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.FreqPushButton.setObjectName("FreqPushButton")
        self.verticalLayout_6.addWidget(self.FreqPushButton)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Freqdisplay = QtWidgets.QLCDNumber(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Freqdisplay.sizePolicy().hasHeightForWidth())
        self.Freqdisplay.setSizePolicy(sizePolicy)
        self.Freqdisplay.setLineWidth(1)
        self.Freqdisplay.setDigitCount(5)
        self.Freqdisplay.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Freqdisplay.setObjectName("Freqdisplay")
        self.horizontalLayout_5.addWidget(self.Freqdisplay)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.MeasurementTimeLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.MeasurementTimeLabel_2.setObjectName("MeasurementTimeLabel_2")
        self.verticalLayout_6.addWidget(self.MeasurementTimeLabel_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.TimeSetDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeSetDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.TimeSetDoubleSpinBox.setSizePolicy(sizePolicy)
        self.TimeSetDoubleSpinBox.setMaximum(60.0)
        self.TimeSetDoubleSpinBox.setProperty("value", 1.0)
        self.TimeSetDoubleSpinBox.setObjectName("TimeSetDoubleSpinBox")
        self.horizontalLayout_6.addWidget(self.TimeSetDoubleSpinBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.statusLabel = QtWidgets.QLabel(Form)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_3.addWidget(self.statusLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Trigger Settings"))
        self.groupBox_4.setTitle(_translate("Form", "Input"))
        self.inputDisablePushButton.setText(_translate("Form", "Input Disable"))
        self.SetGainlabel_2.setText(_translate("Form", "Pre gain:"))
        self.Gaindropdown.setCurrentText(_translate("Form", "1"))
        self.Gaindropdown.setItemText(0, _translate("Form", "1"))
        self.Gaindropdown.setItemText(1, _translate("Form", "2"))
        self.Gaindropdown.setItemText(2, _translate("Form", "4"))
        self.Gaindropdown.setItemText(3, _translate("Form", "8"))
        self.groupBox_3.setTitle(_translate("Form", "Level Set"))
        self.readLevelPushButton.setText(_translate("Form", "Read"))
        self.groupBox.setTitle(_translate("Form", "Optimise Level"))
        self.optimisePushButton.setText(_translate("Form", "Optimise "))
        self.label_2.setText(_translate("Form", "Min Freq [Hz]"))
        self.groupBox_2.setTitle(_translate("Form", "Output Freq"))
        self.FreqPushButton.setText(_translate("Form", "Measure"))
        self.label_5.setText(_translate("Form", "Hz"))
        self.MeasurementTimeLabel_2.setText(_translate("Form", "Gate Time"))
        self.label_6.setText(_translate("Form", "  s"))
        self.statusLabel.setText(_translate("Form", "Sending "))

